<script type="text/javascript" src="{{asset('assets/admin/js/custom.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/js/common.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/js/select2.min.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/js/jquery.datetimepicker.full.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/js/jquery-ui.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/js/jquery.filer.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/ckeditor/ckeditor.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/ckeditor/adapters/jquery.js')}}"></script>
<script type="text/javascript" src="{{asset('assets/admin/js/pnotify.custom.min.js')}}"></script>